Repository fedora-infra/mote, pull requests merged in 2020-10, with the labels that each got.

#137 ci: Modernize Travis CI config
  .travis.yml
Labels: D: quality assurance, T: improvement

#135 Containerization
  Pipfile
  Pipfile.lock
Labels: A: needs info, D: contributor experience, T: new change

#141 Documentation to run møte on Py3
  README.md
Labels: D: contributor experience, blocked, documentation

#133 Updated footer in base.html
  mote/templates/base.html
Labels: T: bug

#144 Pipfile: Upgrade env to Python 3.9
  .travis.yml
  Pipfile
  Pipfile.lock
Labels: T: new change, dependencies
